# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ClientUI(object):
    def setupUi(self, ClientUI):
        ClientUI.setObjectName("ClientUI")
        ClientUI.resize(1072, 626)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        ClientUI.setFont(font)
        ClientUI.setMouseTracking(True)
        ClientUI.setFocusPolicy(QtCore.Qt.TabFocus)
        ClientUI.setStyleSheet("font: 75 11pt \"Times New Roman\";")
        self.centralwidget = QtWidgets.QWidget(ClientUI)
        self.centralwidget.setObjectName("centralwidget")
        self.connect_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.connect_pushButton.setGeometry(QtCore.QRect(900, 10, 81, 21))
        self.connect_pushButton.setObjectName("connect_pushButton")
        self.lineEdit_host = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_host.setGeometry(QtCore.QRect(50, 10, 171, 21))
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.lineEdit_Password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Password.setGeometry(QtCore.QRect(620, 10, 113, 21))
        self.lineEdit_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 47, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 10, 81, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(550, 10, 71, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit_Port = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Port.setGeometry(QtCore.QRect(832, 10, 61, 21))
        self.lineEdit_Port.setObjectName("lineEdit_Port")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(790, 10, 47, 21))
        self.label_4.setObjectName("label_4")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(60, 50, 461, 31))
        self.status_label.setText("")
        self.status_label.setObjectName("status_label")
        self.localDir_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.localDir_lineEdit.setEnabled(False)
        self.localDir_lineEdit.setGeometry(QtCore.QRect(10, 80, 451, 21))
        self.localDir_lineEdit.setObjectName("localDir_lineEdit")
        self.remoteDir_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.remoteDir_lineEdit.setEnabled(False)
        self.remoteDir_lineEdit.setGeometry(QtCore.QRect(570, 80, 421, 21))
        self.remoteDir_lineEdit.setObjectName("remoteDir_lineEdit")
        self.lineEdit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_username.setGeometry(QtCore.QRect(360, 10, 171, 21))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(False)
        self.progressBar.setGeometry(QtCore.QRect(540, 60, 521, 20))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.Quit_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Quit_pushButton.setGeometry(QtCore.QRect(990, 10, 71, 21))
        self.Quit_pushButton.setObjectName("Quit_pushButton")
        self.localDir_treeView = QtWidgets.QTreeView(self.centralwidget)
        self.localDir_treeView.setGeometry(QtCore.QRect(10, 110, 521, 451))
        self.localDir_treeView.setObjectName("localDir_treeView")
        self.remoteDir_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.remoteDir_tableWidget.setGeometry(QtCore.QRect(540, 110, 521, 451))
        self.remoteDir_tableWidget.setAutoScrollMargin(19)
        self.remoteDir_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.remoteDir_tableWidget.setTabKeyNavigation(False)
        self.remoteDir_tableWidget.setProperty("showDropIndicator", False)
        self.remoteDir_tableWidget.setDragDropOverwriteMode(False)
        self.remoteDir_tableWidget.setAlternatingRowColors(False)
        self.remoteDir_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.remoteDir_tableWidget.setShowGrid(False)
        self.remoteDir_tableWidget.setObjectName("remoteDir_tableWidget")
        self.remoteDir_tableWidget.setColumnCount(0)
        self.remoteDir_tableWidget.setRowCount(0)
        self.btn_refreshRemoteDir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_refreshRemoteDir.setGeometry(QtCore.QRect(990, 80, 71, 23))
        self.btn_refreshRemoteDir.setObjectName("btn_refreshRemoteDir")
        self.btn_RefreshLocalDir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_RefreshLocalDir.setGeometry(QtCore.QRect(460, 80, 71, 23))
        self.btn_RefreshLocalDir.setObjectName("btn_RefreshLocalDir")
        self.dirName_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.dirName_lineEdit.setGeometry(QtCore.QRect(620, 560, 301, 20))
        self.dirName_lineEdit.setObjectName("dirName_lineEdit")
        self.btn_createDir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_createDir.setGeometry(QtCore.QRect(920, 560, 71, 23))
        self.btn_createDir.setObjectName("btn_createDir")
        self.label_foldername = QtWidgets.QLabel(self.centralwidget)
        self.label_foldername.setEnabled(False)
        self.label_foldername.setGeometry(QtCore.QRect(510, 560, 131, 21))
        self.label_foldername.setAlignment(QtCore.Qt.AlignCenter)
        self.label_foldername.setObjectName("label_foldername")
        self.btn_Cancell_createDir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Cancell_createDir.setGeometry(QtCore.QRect(990, 560, 71, 23))
        self.btn_Cancell_createDir.setObjectName("btn_Cancell_createDir")
        self.up_downLoadlabel = QtWidgets.QLabel(self.centralwidget)
        self.up_downLoadlabel.setGeometry(QtCore.QRect(540, 40, 511, 20))
        self.up_downLoadlabel.setText("")
        self.up_downLoadlabel.setObjectName("up_downLoadlabel")
        self.conStatus = QtWidgets.QLabel(self.centralwidget)
        self.conStatus.setGeometry(QtCore.QRect(10, 50, 51, 21))
        self.conStatus.setText("")
        self.conStatus.setObjectName("conStatus")
        self.Back_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Back_pushButton.setGeometry(QtCore.QRect(540, 80, 31, 23))
        self.Back_pushButton.setObjectName("Back_pushButton")
        ClientUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ClientUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1072, 23))
        self.menubar.setObjectName("menubar")
        ClientUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ClientUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        ClientUI.setStatusBar(self.statusbar)

        self.retranslateUi(ClientUI)
        QtCore.QMetaObject.connectSlotsByName(ClientUI)

    def retranslateUi(self, ClientUI):
        _translate = QtCore.QCoreApplication.translate
        ClientUI.setWindowTitle(_translate("ClientUI", "FTP"))
        self.connect_pushButton.setText(_translate("ClientUI", "Connect"))
        self.lineEdit_host.setText(_translate("ClientUI", "dlab99"))
        self.lineEdit_Password.setText(_translate("ClientUI", "Seth107"))
        self.label.setText(_translate("ClientUI", "Host :"))
        self.label_2.setText(_translate("ClientUI", "Username :"))
        self.label_3.setText(_translate("ClientUI", "Password :"))
        self.lineEdit_Port.setText(_translate("ClientUI", "21"))
        self.label_4.setText(_translate("ClientUI", "Port :"))
        self.lineEdit_username.setText(_translate("ClientUI", "Madix"))
        self.Quit_pushButton.setText(_translate("ClientUI", "Quit"))
        self.remoteDir_tableWidget.setSortingEnabled(True)
        self.btn_refreshRemoteDir.setText(_translate("ClientUI", "Refresh"))
        self.btn_RefreshLocalDir.setText(_translate("ClientUI", "Refresh"))
        self.btn_createDir.setText(_translate("ClientUI", "Create"))
        self.label_foldername.setText(_translate("ClientUI", "Folder Name"))
        self.btn_Cancell_createDir.setText(_translate("ClientUI", "Cancel"))
        self.Back_pushButton.setText(_translate("ClientUI", "<-"))

